# Generated by Django 4.1.13 on 2023-12-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='291264008237', max_length=15, verbose_name='код из письма'),
        ),
    ]
