# Generated by Django 4.1.13 on 2023-12-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mailing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='id_mailing',
            field=models.IntegerField(blank=True, null=True, verbose_name='id рассылки'),
        ),
    ]
