# Generated by Django 4.1.13 on 2023-12-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_mailinglog_id_mailing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailinglog',
            old_name='mailing_list',
            new_name='mailing_current',
        ),
    ]
