# Generated by Django 4.1.13 on 2023-12-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_rename_mailing_list_mailinglog_mailing_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglog',
            name='id_mailing',
        ),
    ]
