# Generated by Django 4.1.13 on 2023-12-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_remove_mailinglog_client_alter_mailinglog_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['name'], 'verbose_name': 'письмо', 'verbose_name_plural': 'письма'},
        ),
        migrations.AlterModelOptions(
            name='mailinglog',
            options={'ordering': ['-time_try'], 'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='day',
            field=models.IntegerField(blank=True, help_text='Введите число при периодичности раз в месяц. Число должно быть от 1 до 31', null=True, verbose_name='день'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='time_end',
            field=models.TimeField(help_text='Введите время в формате ЧЧ:ММ через  двоеточие. Начало времени отправки быть раньше окончания времени отправки ', verbose_name='окончание времени отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='time_start',
            field=models.TimeField(help_text='Введите время в формате ЧЧ:ММ через двоеточие. Начало времени отправки быть раньше окончания времени отправки ', verbose_name='начало времени отправки'),
        ),
    ]
